/*
 * dio_cfg.c
 *
 * Created: 01-10-2018 06:09:59 PM
 *  Author: New User
 */ 

#include "dio_cfg.h"

DioConfig_t config[] = {
	{PORT1_0, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT1_1, DIO_PULLUP_DISABLED, DIO_INPUT},
	{PORT1_2, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT1_3, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT1_4, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT1_5, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT1_6, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT1_7, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT2_0, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT2_1, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT2_2, DIO_PULLUP_DISABLED, DIO_INPUT},
	{PORT2_3, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT2_4, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT2_5, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT2_6, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT2_7, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT3_0, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT3_1, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT3_2, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT3_3, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT3_4, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT3_5, DIO_PULLUP_DISABLED, DIO_OUTPUT},
	{PORT3_6, DIO_PULLUP_DISABLED, DIO_INPUT},
	{PORT3_7, DIO_PULLUP_DISABLED, DIO_OUTPUT}
};

DioConfig_t const * const Dio_ConfigGet(void)
{
	/*
	* The cast is performed to ensure that the address of the first element of
	* configuration table is returned as a constant pointer and NOT a pointer
	* that can be modified.
	*/
	return (const *)config;
}
